spring:
   profiles:
      active:  dev

---
spring:
   profiles:  dev   #开发环境
   application:
      name: microservicecliud-config-xiyan-dev
---
spring:
   profiles:  test   #测试环境
   application:
      name: microservicecliud-config-xiyan-test


# 必须保存为utf-8